### ISSUE TITLE
Generator fails on custom element

### ISSUE THREAD

**Issue by ondrabus** [Kentico/kentico-cloud-graphql-schema-generator#14]
Running type generation on a project with content types containing custom element fails.

"UnhandledPromiseRejectionWarning: Error: Unknown content type element custom
    at C:\Projects\Apollo\cloud-boilerplate-express-apollo\node_modules\kentico-cloud-graphql-schema-generator\_commonjs\schema-generator.js:80:27"

**Comment by Simply007** [comment]
There is a PoC branch:
https://github.com/Kentico/kentico-cloud-graphql-schema-generator/tree/supportCustomElement

I need to confirm some breaking changes with @Enngage
* FieldType -> ElementType https://github.com/Kentico/kentico-cloud-graphql-schema-generator/pull/15/files#diff-01026069ae6f3da076772007c67bda0fL1
* DeliveryConfig format https://github.com/Kentico/kentico-cloud-graphql-schema-generator/pull/15/files#diff-f41e9d04a45c83f3b6f6e630f10117feL17
* What to use instead of Element type: https://github.com/Kentico/kentico-cloud-graphql-schema-generator/pull/15/files#diff-be5cda278e2d9c8a964ae629e6d50b82L45
* testHttpService force to implement retryPromise method: https://github.com/Kentico/kentico-cloud-graphql-schema-generator/pull/15/files#diff-8594465ae71f42f4597074dbc94b45aaL58 -> don't like it

**Comment by Simply007** [comment]
Draft pull request: #15
